name: Actions API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
            python3.9 -m venv venv
            source venv/bin/activate
            python3.9 -m pip install --upgrade pip
            pip3.9 install -r assets/requirements.txt

      - name: Tests
        run: |
            source venv/bin/activate
            pytest
            deactivate